# Generated by Django 4.2 on 2024-08-18 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='place_id',
        ),
    ]
