# Generated by Django 4.2 on 2024-08-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='description_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=55.75222, max_digits=9),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=37.61556, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
