# Generated by Django 4.2 on 2024-08-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_location_description_long_location_description_short_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=14, default=55.75222, max_digits=17),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=14, default=37.61556, max_digits=17),
        ),
    ]
