# Generated by Django 4.2 on 2024-08-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_location_place_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description_short',
        ),
        migrations.AddField(
            model_name='location',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
