# Generated by Django 4.2 on 2024-08-27 07:42

from django.db import migrations
from django.db.models import Q


def replace_none_with_empty_str(apps, schema_editor):
    Location = apps.get_model('places', 'Location')
    for location in Location.objects.filter(Q(short_description=None) & Q(long_description=None)):
        if location.short_description is None:
            location.short_description = ''
        if location.long_description is None:
            location.long_description = ''
        location.save()

class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_description_long_location_long_description_and_more'),
    ]

    operations = [
        migrations.RunPython(replace_none_with_empty_str)
    ]
