# Generated by Django 4.2 on 2024-08-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='detailsUrl',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='location',
            name='place_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
