# Generated by Django 4.2 on 2024-08-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_location_detailsurl_location_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='detailsUrl',
            field=models.CharField(default='', max_length=100),
        ),
    ]
