# Generated by Django 4.2 on 2024-08-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_location_detailsurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=14, default=55.75222, max_digits=18),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=14, default=37.61556, max_digits=18),
        ),
    ]
