# Generated by Django 4.2 on 2024-08-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='url',
        ),
    ]
