# Generated by Django 4.2 on 2024-08-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_rename_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ManyToManyField(related_name='images', to='places.image'),
        ),
    ]
