# Generated by Django 4.2 on 2024-08-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_location_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ManyToManyField(related_name='locations', to='places.image'),
        ),
    ]
