# Generated by Django 4.2 on 2024-08-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_location_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='filename',
        ),
    ]
